// Generated by CoffeeScript 1.9.3
(function() {
  Template.campaigns.helper = function() {
    return {
      campaigns: function() {
        return Campaigns.find({});
      }
    };
  };

}).call(this);
